buildscript {
    repositories {
        google()
        mavenCentral()
        maven {
            url "https://repo.dairy.foundation/releases"
        }
    }
    dependencies {
        classpath "dev.frozenmilk:Load:0.3.1"
    }
}

apply plugin: 'com.android.application'

//Sloth Load plugin
apply plugin: 'dev.frozenmilk.sinister.sloth.load'

// Include common definitions from above.
apply from: '../build.common.gradle'
apply from: '../build.dependencies.gradle'

android {
    namespace = 'org.firstinspires.ftc.teamcode'

    compileSdk 35
    defaultConfig {
        minSdk 24
    }
    packagingOptions {
        jniLibs.useLegacyPackaging true
    }
}

dependencies {
    implementation project(':FtcRobotController')
}
